name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: NickelHome
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: Build
      uses: docker://ghcr.io/pgaskin/nickeltc:1.0
      with:
        entrypoint: make
        args: all koboroot
    - name: Create draft release
      env:
        GH_TOKEN: ${{ github.token }}
        TAG_NAME: ${{ github.ref_name }}
      run: |
        gh release create "$TAG_NAME" KoboRoot.tgz \
          --draft \
          --generate-notes \
          --title "NickelHome ${TAG_NAME}"
